/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Util.Util;
import controller.CaixaJpaController;
import controller.LancamentoJpaController;
import controller.LancamentoPagfuncJpaController;
import controller.exceptions.PreexistingEntityException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Caixa;
import model.Funcionario;
import model.Lancamento;
import model.LancamentoPagfunc;

/**
 *
 * @author Luis
 */
public class FinalizarPagamentoFuncionario extends javax.swing.JInternalFrame {

    private static Funcionario func = null;
    private static Date dat = null;

    /**
     * Creates new form FinalizarPagamentoFuncionario
     */
    public FinalizarPagamentoFuncionario() {
        initComponents();
        InterfaceUtils.preparaTela(this);

    }

    public FinalizarPagamentoFuncionario(Funcionario funcionario, Date ParamData) {
        initComponents();
        InterfaceUtils.preparaTela(this);
        this.func = funcionario;
        this.dat = ParamData;
        nomeFuncionario.setText(funcionario.getNome());
        data.setText(Util.DateToString(ParamData));
        salario.setText(String.valueOf(funcionario.getSalario()).replace(".", ","));
        total.setText(String.valueOf(funcionario.getSalario()).replace(".", ","));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bonificacao = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento de Funcionário");

        jLabel1.setText("Funcionário: ");

        nomeFuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeFuncionario.setText("none");

        jLabel2.setText("Data:");

        data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        data.setText("none");

        jLabel4.setText("Salário:");

        jLabel5.setText("Bonificação:");

        salario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salario.setText("none");

        jLabel6.setText("Total:");

        total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total.setText("none");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bonificacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bonificacaoFocusLost(evt);
            }
        });
        bonificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bonificacaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bonificacaoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonificacaoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFuncionario)
                    .addComponent(data)
                    .addComponent(salario)
                    .addComponent(total)
                    .addComponent(bonificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(data))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(salario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bonificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new PagamentoFuncionario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LancamentoJpaController lancController = new LancamentoJpaController(ipsum2.Ipsum2.getFactory());
        LancamentoPagfuncJpaController pagFunController = new LancamentoPagfuncJpaController(ipsum2.Ipsum2.getFactory());
        CaixaJpaController caixaController = new CaixaJpaController(ipsum2.Ipsum2.getFactory());
        Caixa caixa = (Caixa) caixaController.getEntityManager().createNamedQuery("Caixa.findAll").getSingleResult();
        Lancamento lanc = new Lancamento();
        LancamentoPagfunc pagFunc = new LancamentoPagfunc();
        lanc.setAtivo((short) 1);
        lanc.setCodcaixa(caixa);
        lanc.setDescricao("Pagamento do Funcionário: "+this.func.getNome());
        lanc.setCodlanc(lancController.getLancamentoCount() + 1);
        lanc.setEstorno((short) 0);
        lanc.setValor(Double.parseDouble(total.getText().replace(",", ".")));
        try {
            lancController.create(lanc);
        } catch (Exception ex) {
            Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

        pagFunc.setBonif(Double.parseDouble(bonificacao.getText().replace(",", ";")));
        pagFunc.setCodfunc(this.func);
        pagFunc.setCodlanc(lanc.getCodlanc());
        pagFunc.setData(this.dat);
        pagFunc.setLancamento(lanc);
        try {
            pagFunController.create(pagFunc);
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bonificacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bonificacaoFocusLost

    }//GEN-LAST:event_bonificacaoFocusLost

    private void bonificacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonificacaoKeyPressed

    }//GEN-LAST:event_bonificacaoKeyPressed

    private void bonificacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonificacaoKeyTyped
//        bonificacao.setText(bonificacao.getText().replace(".", ","));
//        double Tt = this.func.getSalario();
//        Tt = Tt + Double.parseDouble(bonificacao.getText().replace(",", "."));
//        total.setText(String.valueOf(Tt).replace(".", ","));
    }//GEN-LAST:event_bonificacaoKeyTyped

    private void bonificacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonificacaoKeyReleased
        bonificacao.setText(bonificacao.getText().replace(".", ","));
        double Tt = this.func.getSalario();
        try {
            Tt = Tt + Double.parseDouble(bonificacao.getText().replace(",", "."));
        } catch (Exception e) {
        }
        total.setText(String.valueOf(Tt).replace(".", ","));
    }//GEN-LAST:event_bonificacaoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarPagamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarPagamentoFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonificacao;
    private javax.swing.JLabel data;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JLabel salario;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
