/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FornecedorJpaController;
import controller.MaterialJpaController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import model.Fornecedor;
import model.Material;
import Util.*;
import enuns.Permissoes;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author Maicon
 */
public class MaterialCRUDEdit extends javax.swing.JInternalFrame {

    /**
     * Creates new form MaterialCRUD
     */
    private FornecedorJpaController fctr;
    private Boolean isEditing = null;
    private Material mobj;

    public MaterialCRUDEdit() {
        initComponents();
        initFornec();
    }

    public MaterialCRUDEdit(Material m) {
        initComponents();
        initFornec();
        this.isEditing = true;
        this.mobj = m;
        desc.setText(m.getDescricao());
        qtde.setText(m.getQtde().toString());
        jativo.setSelected(m.getAtivo() == 1);
        comboFor.setSelectedItem(m.getCodfornec());
    }

    private void initFornec() {
        fctr = new FornecedorJpaController(ipsum2.Ipsum2.getFactory());
        List<Fornecedor> lstfnc = fctr.findFornecedorEntities();
        ComboBoxModel combofnc = new DefaultComboBoxModel(lstfnc.toArray());
        comboFor.setModel(combofnc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtde = new javax.swing.JTextField();
        comboFor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jativo = new javax.swing.JCheckBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar/Alterar");

        jLabel1.setText("Descrição:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Fornecedor:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jativo.setSelected(true);
        jativo.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(qtde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jativo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFor, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MaterialJpaController matct = new MaterialJpaController(ipsum2.Ipsum2.getFactory());
        boolean passou = true;
        String mensagem = "Não foi possível cadastrar material pois: ";
        if (Util.isNullOrEmpty(desc.getText())) {
            passou = false;
            mensagem = mensagem + "\n Descrição nula";
        }
        if (!Util.VerificaTamanhoStr(desc.getText())) {
            passou = false;
            mensagem = mensagem + "\n Descrição muito pequena";
        }
        try {
            if (!Util.VerificaQuantidade(Integer.parseInt(qtde.getText()))) {
                passou = false;
                mensagem = mensagem + "\n Valor inválido";
            }
        } catch (Exception e) {
            passou = false;
            mensagem = mensagem + "\n Valor inválido";
        }
        if (passou == false) {
            JOptionPane.showMessageDialog(this, mensagem);
        } else {
            if (this.isEditing == null) {
                try {
                    Material novo = new Material();

                    novo.setCodmat(matct.getMaterialCount() + 1);
                    novo.setAtivo(Util.boolToShort(jativo.isSelected()));
                    novo.setCodfornec((Fornecedor) comboFor.getSelectedItem());
                    novo.setDescricao(desc.getText());
                    novo.setQtde(Integer.parseInt(qtde.getText()));

                    matct.create(novo);
                } catch (Exception ex) {
                    Logger.getLogger(MaterialCRUDEdit.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if (!Funcionario.permite(Permissoes.ALTERAR_MATERIAL)) {
                    JOptionPane.showMessageDialog(this, "Você não possui permissão para editar.");
                    return;
                }
                mobj.setQtde(Integer.parseInt(qtde.getText()));
                mobj.setDescricao(desc.getText());
                mobj.setCodfornec((Fornecedor) comboFor.getSelectedItem());
                mobj.setAtivo(Util.boolToShort(jativo.isSelected()));

                try {
                    matct.edit(mobj);
                } catch (Exception ex) {
                    Logger.getLogger(MaterialCRUDEdit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            MaterialCRUD reload = new MaterialCRUD();
            Start.addFrame(reload);
            reload.setLocation(10, 10);
            reload.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterialCRUDEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterialCRUDEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterialCRUDEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialCRUDEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaterialCRUDEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboFor;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jativo;
    private javax.swing.JTextField qtde;
    // End of variables declaration//GEN-END:variables
}
